import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: autoscaling
export async function get_autoscaling<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/autoscaling', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/autoscaling', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_policy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/autoscaling/policy', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_schedulepolicy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/schedulepolicy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_policy_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/policy/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_policy_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/policy/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
