import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: cloud
export async function get_cloud<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/cloud/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_cloud_cloudid<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/cloud/${cloudid}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_deploy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/cloud/deploy/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_cloud_images<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/cloud/images', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_cloud_cloudid_resizeplans<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/cloud/${cloudid}/resizeplans/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_snapshot_create<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/create/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_cloud_cloudid_snapshot_snapshotid_delete<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/cloud/${cloudid}/snapshot/${snapshotid}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_cloud_cloudid_destroy<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/cloud/${cloudid}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_backups_disable<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/backups/disable`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_backups_enable<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/backups/enable`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_billingcycle<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/billingcycle`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_hardreboot<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/hardreboot/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_powercycle<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/powercycle/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_poweroff<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/poweroff/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_poweron<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/poweron/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_rebuild<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/rebuild/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_resetpassword<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/resetpassword/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_resize<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/resize/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_snapshot_snapshotid_restore<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/${snapshotid}/restore/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_storage_storageid_update<T = unknown>(client: ApiClient, cloudid: string, storageid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/storage/${storageid}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_assignpublicip<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/assignpublicip`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloud_id_updaterdns_ip_address<T = unknown>(client: ApiClient, cloud_id: string, ip_address: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloud_id}/updaterdns/${ip_address}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_cloud_1637583_ip_public_ip_delete<T = unknown>(client: ApiClient, public_ip: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/cloud/1637583/ip/${public_ip}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_enablerescue<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/enablerescue`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_disablerescue<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/disablerescue`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_mountiso<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/mountiso`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_umountiso<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/umountiso`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_snapshot_snapshotid_restore_2<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/${snapshotid}/restore`, query: options?.query, body: options?.body, headers: options?.headers }); }
