import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: databases
export async function get_databases<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/databases', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/databases', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_databases_cluster_id<T = unknown>(client: ApiClient, cluster_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/databases/${cluster_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_id_database<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${id}/database`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_databases_id_database_dbname<T = unknown>(client: ApiClient, id: string, dbname: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/databases/${id}/database/${dbname}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_id_user<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${id}/user`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_databases_db_id_user<T = unknown>(client: ApiClient, db_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/databases/${db_id}/user`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_id_database_dbname_user<T = unknown>(client: ApiClient, id: string, dbname: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${id}/database/${dbname}/user`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_id_trustedhost<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${id}/trustedhost/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_databases_id_trustedhost_trustedhost_ip<T = unknown>(client: ApiClient, id: string, trustedhost_ip: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/databases/${id}/trustedhost/${trustedhost_ip}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_databases_db_id_cloud_id_certificate<T = unknown>(client: ApiClient, db_id: string, cloud_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/databases/${db_id}/${cloud_id}/certificate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_db_id_backup<T = unknown>(client: ApiClient, db_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${db_id}/backup`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_databases_db_id_securitygroup_firewall_id<T = unknown>(client: ApiClient, db_id: string, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/databases/${db_id}/securitygroup/${firewall_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_databases_db_id_securitygroup_firewall_id<T = unknown>(client: ApiClient, db_id: string, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/databases/${db_id}/securitygroup/${firewall_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_databases_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/databases/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
