import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: firewall
export async function get_firewall<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/firewall', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_firewall_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/firewall/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/firewall/create', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_firewall_id_rule_add<T = unknown>(client: ApiClient, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/firewall/${firewall_id}/rule/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_firewall_id_rule_rule_id_delete<T = unknown>(client: ApiClient, firewall_id: string, rule_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${firewall_id}/rule/${rule_id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_firewall_id_server_add<T = unknown>(client: ApiClient, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/firewall/${firewall_id}/server/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_id_server_cloudid_delete<T = unknown>(client: ApiClient, id: string, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${id}/server/${cloudid}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
