import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: kubernetes
export async function get_kubernetes_k8_id<T = unknown>(client: ApiClient, k8_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/kubernetes/${k8_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_deploy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/kubernetes/deploy', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_kubernetes_id_download<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/kubernetes/${id}/download`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_start<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/start`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_nodepool_id_update<T = unknown>(client: ApiClient, id: string, nodepool_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/nodepool/{id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_k8_id_nodepool_ipool_id_update<T = unknown>(client: ApiClient, k8_id: string, ipool_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${k8_id}/nodepool/${ipool_id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_k8_id_nodepool_add<T = unknown>(client: ApiClient, k8_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${k8_id}/nodepool/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
