import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: loadbalancer
export async function post_loadbalancer_id_acl<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/acl/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_route<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/route/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_backend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/backend/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_frontend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/frontend`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_frontend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/frontend`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_add<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/loadbalancer/add/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_acl_acl_id<T = unknown>(client: ApiClient, id: string, acl_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/acl/${acl_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_acl_acl_id<T = unknown>(client: ApiClient, id: string, acl_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/acl/${acl_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_backend_backend_id<T = unknown>(client: ApiClient, id: string, backend_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/backend/${backend_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_frontend_frontend_id<T = unknown>(client: ApiClient, id: string, frontend_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/frontend/${frontend_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_route_route_id<T = unknown>(client: ApiClient, id: string, route_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/route/${route_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_route_route_id<T = unknown>(client: ApiClient, id: string, route_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/route/${route_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/destroy/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_loadbalancer_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/loadbalancer/${id}/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_loadbalancer<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/loadbalancer/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_update<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
