import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: objectstorage
export async function get_objectstorage_dcslug_bucket<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_bucket_name<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket/${name}/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_bucket_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/objectstorage/bucket/create/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_objectstorage_dcslug_bucket_name_delete<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/objectstorage/${dcslug}/bucket/${name}/delete/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_bucket_name_policy_policy_type<T = unknown>(client: ApiClient, dcslug: string, bucket_name: string, policy_type: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${bucket_name}/policy/${policy_type}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_name_permission_selected_permission_accesskey_selected_key<T = unknown>(client: ApiClient, dcslug: string, name: string, selected_permission: string, selected_key: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${name}/permission/${selected_permission}/accesskey/${selected_key}/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_innoida_bucket_bucket_name_objects<T = unknown>(client: ApiClient, bucket_name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/innoida/bucket/${bucket_name}/objects`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_name_createdirectory<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${name}/createdirectory/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_objectstorage_dcslug_bucket_name_delete_object<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/objectstorage/${dcslug}/bucket/${name}/delete/object`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_bucket_name_download<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket/${name}/download`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_innoida_bucket_uthostorage_upload_internal<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/objectstorage/innoida/bucket/uthostorage/upload/internal', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_accesskeys<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/accesskeys/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_accesskey_create<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/accesskey/create`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_accesskey_name_status<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/accesskey/${name}/status`, query: options?.query, body: options?.body, headers: options?.headers }); }
