import { ApiClient } from '../runtime/client.js';
import { EndpointOptions } from './common.js';
// Auto-generated wrappers for segment: vpc
export async function post_vpc_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/create', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_vpc_id<T = unknown>(client: ApiClient, vpc_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/${vpc_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/subnet/create', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_subnet_subnet_id<T = unknown>(client: ApiClient, subnet_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/subnet/${subnet_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_subnet<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc/subnet', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/natgateway', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: '/vpc/natgateway', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc/natgateway', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc/peering', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/peering', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: '/vpc/peering', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_route<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/route', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_associate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/subnet/associate', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_subnet_associate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc/subnet/associate', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_dissociate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/subnet/dissociate', query: options?.query, body: options?.body, headers: options?.headers }); }
