import { ApiClient } from '../runtime/client.js';
// Auto-generated lightweight wrappers. Regenerate with npm run generate

export interface EndpointOptions {
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
}

export async function get_api<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/api', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_api_generate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: '/api/generate', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_api_id_delete<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/api/${id}/delete`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_account_info<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/account/info', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_actions_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: `/actions/${id}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_v2_actions<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/v2/actions/', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_activity<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/activity', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_backups<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/backups', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_databases<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: '/databases', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: '/databases', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_databases_cluster_id<T = unknown>(client: ApiClient, cluster_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: `/databases/${cluster_id}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_id_database<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${id}/database`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_databases_id_database_dbname<T = unknown>(client: ApiClient, id: string, dbname: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/databases/${id}/database/${dbname}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_id_user<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${id}/user`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_databases_db_id_user<T = unknown>(client: ApiClient, db_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/databases/${db_id}/user`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_id_database_dbname_user<T = unknown>(client: ApiClient, id: string, dbname: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${id}/database/${dbname}/user`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_id_trustedhost<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${id}/trustedhost/`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_databases_id_trustedhost_trustedhost_ip<T = unknown>(client: ApiClient, id: string, trustedhost_ip: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/databases/${id}/trustedhost/${trustedhost_ip}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_databases_db_id_cloud_id_certificate<T = unknown>(client: ApiClient, db_id: string, cloud_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: `/databases/${db_id}/${cloud_id}/certificate`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_db_id_backup<T = unknown>(client: ApiClient, db_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${db_id}/backup`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_databases_db_id_securitygroup_firewall_id<T = unknown>(client: ApiClient, db_id: string, firewall_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/databases/${db_id}/securitygroup/${firewall_id}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_databases_db_id_securitygroup_firewall_id<T = unknown>(client: ApiClient, db_id: string, firewall_id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/databases/${db_id}/securitygroup/${firewall_id}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_databases_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/databases/${id}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_dns<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'GET', path: '/dns', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_dns_domain<T = unknown>(client: ApiClient, domain: string, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'GET', path: `/dns/${domain}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_dns_adddomain<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'POST', path: '/dns/adddomain', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_dns_domain_record_add<T = unknown>(client: ApiClient, domain: string, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'POST', path: `/dns/${domain}/record/add/`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_dns_domain_delete<T = unknown>(client: ApiClient, domain: string, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'DELETE', path: `/dns/${domain}/delete`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_dns_domain_record_recordid_delete<T = unknown>(client: ApiClient, domain: string, recordid: string, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'DELETE', path: `/dns/${domain}/record/${recordid}/delete/`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_cloud<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'GET', path: '/cloud/', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_cloud_cloudid<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'GET', path: `/cloud/${cloudid}`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_deploy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'POST', path: '/cloud/deploy/', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_cloud_images<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> {
  return client.request({ method: 'GET', path: '/cloud/images', query: options?.query, body: options?.body, headers: options?.headers });
}
export async function get_cloud_cloudid_resizeplans<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'GET', path: `/cloud/${cloudid}/resizeplans/`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_cloudid_snapshot_create<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/create/`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_cloud_cloudid_snapshot_snapshotid_delete<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/cloud/${cloudid}/snapshot/${snapshotid}/delete`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function delete_cloud_cloudid_destroy<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'DELETE', path: `/cloud/${cloudid}/destroy`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_cloudid_backups_disable<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/backups/disable`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_cloudid_backups_enable<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/backups/enable`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_cloudid_billingcycle<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> {
  return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/billingcycle`, query: options?.query, body: options?.body, headers: options?.headers });
}
export async function post_cloud_cloudid_hardreboot<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/hardreboot/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_powercycle<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/powercycle/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_poweroff<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/poweroff/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_poweron<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/poweron/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_rebuild<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/rebuild/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_resetpassword<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/resetpassword/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_resize<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/resize/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_snapshot_snapshotid_restore<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/${snapshotid}/restore/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_storage_storageid_update<T = unknown>(client: ApiClient, cloudid: string, storageid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/storage/${storageid}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_assignpublicip<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/assignpublicip`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloud_id_updaterdns_ip_address<T = unknown>(client: ApiClient, cloud_id: string, ip_address: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloud_id}/updaterdns/${ip_address}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_cloud_1637583_ip_public_ip_delete<T = unknown>(client: ApiClient, public_ip: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/cloud/1637583/ip/${public_ip}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_enablerescue<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/enablerescue`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_disablerescue<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/disablerescue`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_mountiso<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/mountiso`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_umountiso<T = unknown>(client: ApiClient, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/umountiso`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_firewall<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/firewall', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_firewall_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/firewall/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/firewall/create', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_firewall_id_rule_add<T = unknown>(client: ApiClient, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/firewall/${firewall_id}/rule/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_firewall_id_rule_rule_id_delete<T = unknown>(client: ApiClient, firewall_id: string, rule_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${firewall_id}/rule/${rule_id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_firewall_firewall_id_server_add<T = unknown>(client: ApiClient, firewall_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/firewall/${firewall_id}/server/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_id_server_cloudid_delete<T = unknown>(client: ApiClient, id: string, cloudid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${id}/server/${cloudid}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_firewall_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/firewall/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_iso<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/iso', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_iso_add<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/iso/add', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_iso_id_delete<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/iso/${id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_v2_kubernetes<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/v2/kubernetes', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_kubernetes_k8_id<T = unknown>(client: ApiClient, k8_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/kubernetes/${k8_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_deploy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/kubernetes/deploy', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_kubernetes_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/kubernetes/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_kubernetes_id_download<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/kubernetes/${id}/download`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_v2_kubernetes_id_stop<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/v2/kubernetes/${id}/stop`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_start<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/start`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_id_nodepool_id_update<T = unknown>(client: ApiClient, id: string, nodepool_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${id}/nodepool/${nodepool_id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_k8_id_nodepool_ipool_id_update<T = unknown>(client: ApiClient, k8_id: string, ipool_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${k8_id}/nodepool/${ipool_id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_kubernetes_k8_id_nodepool_add<T = unknown>(client: ApiClient, k8_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/kubernetes/${k8_id}/nodepool/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_acl<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/acl/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_route<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/route/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_backend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/backend/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_id_frontend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/loadbalancer/${id}/frontend`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_frontend<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/frontend`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_loadbalancer_add<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/loadbalancer/add/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_acl_acl_id<T = unknown>(client: ApiClient, id: string, acl_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/acl/${acl_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_acl_acl_id<T = unknown>(client: ApiClient, id: string, acl_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/acl/${acl_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_backend_backend_id<T = unknown>(client: ApiClient, id: string, backend_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/backend/${backend_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_frontend_frontend_id<T = unknown>(client: ApiClient, id: string, frontend_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/frontend/${frontend_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_route_route_id<T = unknown>(client: ApiClient, id: string, route_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/route/${route_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_route_route_id<T = unknown>(client: ApiClient, id: string, route_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/route/${route_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_loadbalancer_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/loadbalancer/${id}/destroy/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_loadbalancer_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/loadbalancer/${id}/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_loadbalancer<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/loadbalancer/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_loadbalancer_id_update<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/loadbalancer/${id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_sqs<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/sqs', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_sqs<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/sqs', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_sqs_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/sqs/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_sqs_sqs_id_destroy<T = unknown>(client: ApiClient, sqs_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/sqs/${sqs_id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_sqs_id_queue<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/sqs/${id}/queue`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_key<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/key', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_key_import<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/key/import', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_key_id_delete<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/key/${id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_snapshot<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/snapshot', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_cloud_cloudid_snapshot_snapshotid_restore_2<T = unknown>(client: ApiClient, cloudid: string, snapshotid: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/cloud/${cloudid}/snapshot/${snapshotid}/restore`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_user<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/user', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_user<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/user', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_user_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/user/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_user_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/user/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_user_subuser_id<T = unknown>(client: ApiClient, subuser_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/user/${subuser_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_transfer_process<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/transfer/process/', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_transfer_resource_type_resource_id<T = unknown>(client: ApiClient, resource_type: string, resource_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/transfer/${resource_type}/${resource_id}/`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpc/create', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpc', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpn<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/vpn', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpn_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpn/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpn_deploy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/vpn/deploy', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpn_id_destroy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpn/${id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpn_vpn_id_user_add<T = unknown>(client: ApiClient, vpn_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpn/${vpn_id}/user/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpn_id_user_user_name_download<T = unknown>(client: ApiClient, id: string, user_name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpn/${id}/user/${user_name}/download`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpn_id_user_user_name_remove<T = unknown>(client: ApiClient, id: string, user_name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpn/${id}/user/${user_name}/remove`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_autoscaling<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: '/autoscaling', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/autoscaling', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_policy<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: '/autoscaling/policy', query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_schedulepolicy<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/schedulepolicy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_id_schedulepolicy_schedulepolicy_id<T = unknown>(client: ApiClient, id: string, schedulepolicy_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/${id}/schedulepolicy/${schedulepolicy_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_securitygroup_securitygroup_id<T = unknown>(client: ApiClient, id: string, securitygroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/securitygroup/${securitygroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_autoscaling_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/autoscaling/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_targetgroup_targetgroup_id<T = unknown>(client: ApiClient, id: string, targetgroup_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/targetgroup/${targetgroup_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_policy_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/policy/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_policy_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/policy/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_autoscaling_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/autoscaling/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_autoscaling_id_loadbalancer_loadbalancer_id<T = unknown>(client: ApiClient, id: string, loadbalancer_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/autoscaling/${id}/loadbalancer/${loadbalancer_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_vpc_id<T = unknown>(client: ApiClient, vpc_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/${vpc_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/subnet/create`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_subnet_subnet_id<T = unknown>(client: ApiClient, subnet_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/subnet/${subnet_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_subnet<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/subnet`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/natgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/natgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_natgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/natgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_elasticip<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/elasticip`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_elasticip_allocate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/elasticip/allocate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_elasticip_ip_address_deallocate<T = unknown>(client: ApiClient, ip_address: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/elasticip/${ip_address}/deallocate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/peering`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/peering`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_peering<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/peering`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_route<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/route`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_route<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/route`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_route<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/route`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_internetgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/internetgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_internetgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/internetgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_internetgateway<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/internetgateway`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_internetgateway_id_attach<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/internetgateway/${id}/attach`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_internetgateway_234236_dettach<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/internetgateway/234236/dettach`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_route_table<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/route/table`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_vpc_route_table<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/vpc/route/table`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_route_table<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/route/table`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_associate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/subnet/associate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_vpc_subnet_associate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/vpc/subnet/associate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_vpc_subnet_dissociate<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/vpc/subnet/dissociate`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_stacks<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/stacks`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_stacks<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/stacks`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_stacks_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/stacks/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_stacks_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/stacks/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_certificates<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/certificates`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_certificates<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/certificates`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_certificates_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/certificates/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_pricing_objectstorage<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/pricing/objectstorage`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_bucket<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_bucket_name<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket/${name}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_bucket_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/bucket/create`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_objectstorage_dcslug_bucket_name_delete<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/objectstorage/${dcslug}/bucket/${name}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_bucket_name_policy_policy_type<T = unknown>(client: ApiClient, dcslug: string, bucket_name: string, policy_type: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${bucket_name}/policy/${policy_type}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_name_permission_selected_permission_accesskey_selected_key<T = unknown>(client: ApiClient, dcslug: string, name: string, selected_permission: string, selected_key: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${name}/permission/${selected_permission}/accesskey/${selected_key}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_innoida_bucket_bucket_name_objects<T = unknown>(client: ApiClient, bucket_name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/innoida/bucket/${bucket_name}/objects`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_bucket_name_createdirectory<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/bucket/${name}/createdirectory`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_objectstorage_dcslug_bucket_name_delete_object<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/objectstorage/${dcslug}/bucket/${name}/delete/object`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_bucket_name_download<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/bucket/${name}/download`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_innoida_bucket_uthostorage_upload_internal<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/innoida/bucket/uthostorage/upload/internal`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_objectstorage_dcslug_accesskeys<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/objectstorage/${dcslug}/accesskeys`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_accesskey_create<T = unknown>(client: ApiClient, dcslug: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/accesskey/create`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_objectstorage_dcslug_accesskey_name_status<T = unknown>(client: ApiClient, dcslug: string, name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/objectstorage/${dcslug}/accesskey/${name}/status`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_ebs<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/ebs`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_ebs<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/ebs`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_ebs_id_resize<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/ebs/${id}/resize`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_ebs_storage_id_destroy<T = unknown>(client: ApiClient, storage_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/ebs/storage/${storage_id}/destroy`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_ebs_storage_id_attach<T = unknown>(client: ApiClient, storage_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/ebs/storage/${storage_id}/attach`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_ebs_storage_id_dettach<T = unknown>(client: ApiClient, storage_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/ebs/storage/${storage_id}/dettach`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_registry_projects<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/registry/projects`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_registry<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/registry`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_registry<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/registry`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_registry_project_registry_name<T = unknown>(client: ApiClient, registry_name: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/registry/project/${registry_name}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_alert_contact_list<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/alert/contact/list`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_alert_contact_add<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/alert/contact/add`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_alert_contact_id_update<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/alert/contact/${id}/update`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_alert_contact_id_delete<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/alert/contact/${id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_alert<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/alert`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_alert<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/alert`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/alert/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_alert_alert_id_delete<T = unknown>(client: ApiClient, alert_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/alert/${alert_id}/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_targetgroup<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/targetgroup`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_targetgroup<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/targetgroup`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_targetgroup_target_group_id<T = unknown>(client: ApiClient, target_group_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/targetgroup/${target_group_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_targetgroup_id<T = unknown>(client: ApiClient, id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/targetgroup/${id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_targetgroup_target_group_id_target<T = unknown>(client: ApiClient, target_group_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/targetgroup/${target_group_id}/target`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_targetgroup_target_group_id_target_target_id<T = unknown>(client: ApiClient, target_group_id: string, target_id: string, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/targetgroup/${target_group_id}/target/${target_id}`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_ipsec<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/ipsec`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_ipsec<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/ipsec`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_ipsec<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/ipsec`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function put_ipsec<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'PUT', path: `/ipsec`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function get_waf_list<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'GET', path: `/waf/list`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_create<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/create`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_attach_rule<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/attach-rule`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_detach_rule<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/detach-rule`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_create_ruleset<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/create-ruleset`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_add_rule<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/add-rule`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function post_waf_create_waf_instance<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'POST', path: `/waf/create-waf-instance`, query: options?.query, body: options?.body, headers: options?.headers }); }
export async function delete_waf_delete<T = unknown>(client: ApiClient, options?: EndpointOptions): Promise<T> { return client.request<T>({ method: 'DELETE', path: `/waf/delete`, query: options?.query, body: options?.body, headers: options?.headers }); }
